---
kind: pipeline
name: lint

steps:
- name: lint
  pull: always
  image: alpine:3.13
  commands:
    - ls -l
    - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
    - helm lint helm-chart-sources/*

# - name: discord
#   pull: always
#   image: appleboy/drone-discord:1.2.4
#   environment:
#     DISCORD_WEBHOOK_ID:
#       from_secret: discord_webhook_id
#     DISCORD_WEBHOOK_TOKEN:
#       from_secret: discord_webhook_token
#   when:
#     status:
#     - changed
#     - failure

---
kind: pipeline
name: release-version

# trigger:
#   event:
#     - tag

steps:
  - name: generate-chart
    pull: always
    image: alpine:3.13
    commands:
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
      - apk add --no-cache curl
      - apk add --no-cache git
      - helm dependency update helm-chart-sources/*
      - helm package helm-chart-sources/*
      - git clone https://github.com/Frantche/helm-chart.git
      - mv -n *.tgz helm-chart/
      - mv -n *.yaml helm-chart/
      # - mv /helm-chart-sources/* helm-chart/helm-chart-sources/
      #  - mkdir gitea
      # - mv gitea*.tgz gitea/
      - ls -l
      - ls -l helm-chart
      - ls -l helm-chart/helm-chart-sources/
      - echo ${github_token}
      - helm repo index helm-chart/ --url https://${github_token}@frantche.github.io/helm-chart/ --merge helm-chart/index.yaml
      - git add .
      - git commit -m 'update helm repo'
      - git push