---
kind: pipeline
name: lint

steps:
- name: lint
  pull: always
  image: alpine:3.13
  commands:
    - ls -l
    - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
    - helm lint helm-chart-sources/*

# - name: discord
#   pull: always
#   image: appleboy/drone-discord:1.2.4
#   environment:
#     DISCORD_WEBHOOK_ID:
#       from_secret: discord_webhook_id
#     DISCORD_WEBHOOK_TOKEN:
#       from_secret: discord_webhook_token
#   when:
#     status:
#     - changed
#     - failure

---
kind: pipeline
name: release-version

trigger:
  event:
    - tag

steps:
  - name: generate-chart
    pull: always
    image: alpine:3.13
    environment:
      TOKEN:
        from_secret: github_token
      USER:
        from_secret: github_user
    commands:
      - env
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
      - apk add --no-cache curl
      - apk add --no-cache git
      - helm dependency update helm-chart-sources/gitea
      - helm dependency update helm-chart-sources/whoami
      - helm package helm-chart-sources/*
      - git clone https://$USER:$TOKEN@github.com/Frantche/helm-chart.git
      - mv -n *.tgz helm-chart/
      - mv -n *.yaml helm-chart/
      - helm repo index helm-chart/ --url https://frantche.github.io/helm-chart/ --merge helm-chart/index.yaml
      - cd helm-chart
      - cat index.yaml
      - git add .
      - git config --global user.email "21145306+Frantche@users.noreply.github.com"
      - git config --global user.name "CICD Drone"
      - git commit -m 'update helm repo'
      - git push