{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-backup
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
data:
  BACKUP_TARGET_FOLDER: {{ .Values.backup.BACKUP_TARGET_FOLDER | b64enc }}"full_backup"
  BACKUP_METHODE: {{ .Values.backup.BACKUP_METHODE | b64enc }}"s3"
  ENDPOINT_URL: {{ .Values.backup.ENDPOINT_URL | b64enc }}"https://eu2.contabostorage.com"
  AWS_ACCESS_KEY_ID: {{ .Values.backup.AWS_ACCESS_KEY_ID | b64enc }}"b84f8e7005244c8b94f36cb21a5f749a"
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.AWS_SECRET_ACCESS_KEY | b64enc }}"7755a1228ca6b2ca484bdd69bb13d4a8"
  BACKUP_FILENAME: {{ .Values.backup.BACKUP_FILENAME | b64enc }}"gitea-backup-2023-02-23-19-23-59.zip"
  BACKUP_ENABLE: {{ .Values.backup.BACKUP_ENABLE | b64enc }}"True"
  BUCKET: {{ .Values.backup.BUCKET | b64enc }}gitea-backup
{{- end }}
